name: Bug Report
description: File a bug report
title: "[Bug]: "
body:
    - type: markdown
      attributes:
          value: |
              ## Thanks for taking the time to fill out this bug report!

              We're sorry that you're experiencing an issue. To help us assist you efficiently, please fill out this form to the best of your ability. The more details you provide, the easier it will be for us to resolve the issue.
    - type: dropdown
      attributes:
          label: Which framework are you using?
          description: Select all the frameworks where you are experiencing issues.
          multiple: true
          options:
              - "React"
              - "React (with Tailwind)"
              - "React Native"
              - "React Native (with Expo)"
              - "Angular"
              - "Flutter"
              - "Hardhat"
              - "Truffle"
              - "The Graph"
      validations:
          required: true
    - type: textarea
      attributes:
          label: What happened?
          description: Describe the issue and what you expected to happen.
          placeholder: Tell us what you see!
    - type: textarea
      attributes:
          label: Steps to reproduce
          description: Please provide clearly ordered steps to reproduce the issue.
          placeholder: |
              1. Log in to the system
              2. Click the menu item
              3. Submit
    - type: textarea
      attributes:
          label: Anything else?
          description: |
              Links? References? Any additional context about the issue you are encountering?
              Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
