name: Feature Request
description: Submit a feature request
title: "[Feature]: "
body:
    - type: markdown
      attributes:
          value: |
              ## Thanks for taking the time to submit this feature request!

              We appreciate all ideas and suggestions. The more details you provide, the better we can understand and evaluate your request.
    - type: textarea
      attributes:
          label: Describe your idea
          description: |
              - Provide as much detail as possible to help us understand the change you’d like to see.
              - What is the expected outcome or benefit?
    - type: textarea
      attributes:
          label: Anything else?
          description: |
              Links? References? Any additional context that can help us understand your request.
              Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
